# Generated by Django 4.2.2 on 2023-06-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='grades',
            field=models.CharField(default='', max_length=100),
        ),
    ]
